plugins {
	id "dev.architectury.loom" version "1.10-SNAPSHOT"
	id 'maven-publish'
	id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

version = mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

apply from: 'https://raw.githubusercontent.com/FTBTeam/mods-meta/main/gradle/changelog.gradle'
apply from: "https://raw.githubusercontent.com/FTBTeam/mods-meta/main/gradle/publishing.gradle"

loom {
	silentMojangMappingsLicense()
}

repositories {
	maven {
		url "https://maven.shedaniel.me/"
		content {
			includeGroup "me.shedaniel"
		}
	}

	maven {
		url "https://www.cursemaven.com"
		content {
			includeGroup "curse.maven"
		}
	}

	maven {
		url "https://maven.ftb.dev/releases"
		content {
			includeGroup "dev.ftb.mods"
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
	modImplementation "curse.maven:game-stages-268655:${gamestages_file}"
	modRuntimeOnly "curse.maven:bookshelf-228525:${gamestages_bookshelf_file}"
	modRuntimeOnly "curse.maven:rftools-base-326041:3206945"
	modRuntimeOnly "curse.maven:mcjtylib-233105:3236516"
	modRuntimeOnly "curse.maven:rftools-builder-347706:3302323"
	modRuntimeOnly "curse.maven:rftools-storage-350006:3302324"
	modRuntimeOnly "curse.maven:rftools-utility-342466:3310447"
	modImplementation "dev.ftb.mods:ftb-library-forge:${ftblibrary_version}"
	modImplementation "me.shedaniel:architectury-forge:${arch_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("META-INF/mods.toml") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	def targetVersion = 8
	if (JavaVersion.current().isJava9Compatible()) {
		it.options.release = targetVersion
	}
}

java {
	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archivesBaseName}" }
	}

	manifest {
		attributes([
				"Specification-Title"     : project.mod_id,
				"Specification-Vendor"    : project.mod_author,
				"Specification-Version"   : "1",
				"Implementation-Title"    : project.name,
				"Implementation-Version"  : version,
				"Implementation-Vendor"   : project.mod_author,
				"Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
	}
}

publishing {
	publications {
		mavenForge(MavenPublication) {
			version = ftbPublishing.mavenVersion
			artifactId = rootProject.archivesBaseName
			artifact(remapJar) {
				classifier null
			}
			artifact(sourcesJar) {
				builtBy remapSourcesJar
			}
		}
	}

	repositories {
		if (ftbPublishing.ftbToken) {
			maven {
				url ftbPublishing.ftbURL
				credentials {
					username = ftbPublishing.ftbUser
					password = ftbPublishing.ftbToken
				}
			}
		}
	}
}

publishMods {
	def CFToken = providers.environmentVariable("CURSEFORGE_KEY");

	dryRun = !CFToken.isPresent()
	displayName = "FTB Banners ${project.version}"
	modLoaders.add("forge")

	changelog = createChangelog(project)
	file = remapJar.archiveFile
	version = project.version // Pretty sure it defaults to this

	def tag = providers.environmentVariable("TAG").getOrElse("release")
	type = tag.endsWith("-beta") ? BETA : (tag.endsWith("-alpha") ? ALPHA : STABLE)

	curseforge {
		accessToken = CFToken.orElse("missing")
		projectId = project.curseforge_id
		minecraftVersions.add(project.minecraft_version)
		javaVersions.add(JavaVersion.VERSION_1_8)

		requires("ftb-library-forge")
		requires("architectury-api")
		optional("game-stages")
	}
}