modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All rights reserved"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Banners/issues" #optional
[[mods]] #mandatory
modId = "ftbbanners" #mandatory
version = "${version}" #mandatory
displayName = "FTB Banners" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile = "assets/ftbbanners/textures/logo.png" #optional
credits = "LatvianModder, ErrorMikey" #optional
authors = "FTB Team" #optional
description = '''
Banners with custom images :D
'''
[[dependencies.ftbbanners]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.ftbbanners]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
